package docs

import (
	"path/filepath"
	"testing"
)

func TestLockfileExactPackageLock(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "package.json", `{
	  "dependencies": {"next": "^15.0.0", "react": "^18.0.0"}
	}`)
	write(t, dir, "package-lock.json", `{
	  "name": "app",
	  "lockfileVersion": 3,
	  "packages": {
	    "": {"name": "app"},
	    "node_modules/next": {"version": "15.0.3"},
	    "node_modules/react": {"version": "18.2.0"},
	    "node_modules/@scope/pkg": {"version": "1.2.3"}
	  }
	}`)

	v, eco := ResolveVersion(dir, "next")
	if v != "15.0.3" || eco != "npm" {
		t.Errorf("next lock pin => %q,%q want 15.0.3,npm", v, eco)
	}
	if v2, eco2, lf := ResolveVersionDetail(dir, "next"); v2 != "15.0.3" || eco2 != "npm" || lf != "package-lock.json" {
		t.Errorf("ResolveVersionDetail next => %q,%q,%q want 15.0.3,npm,package-lock.json", v2, eco2, lf)
	}
	// Manifest alone would have normalized ^15.0.0 → 15.0.0; lock must win.
	deps := ListDependencies(dir)
	var next Dependency
	for _, d := range deps {
		if d.Name == "next" {
			next = d
		}
	}
	if next.Version != "15.0.3" || next.Manifest != "package-lock.json" {
		t.Errorf("ListDependencies next = %+v want version 15.0.3 from package-lock.json", next)
	}
}

func TestLockfileExactYarnAndPnpm(t *testing.T) {
	yarnDir := t.TempDir()
	write(t, yarnDir, "package.json", `{"dependencies":{"lodash":"^4.17.0"}}`)
	write(t, yarnDir, "yarn.lock", `# yarn lockfile v1

lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
`)
	if v, eco := ResolveVersion(yarnDir, "lodash"); v != "4.17.21" || eco != "npm" {
		t.Errorf("yarn lodash => %q,%q want 4.17.21,npm", v, eco)
	}

	pnpmDir := t.TempDir()
	write(t, pnpmDir, "package.json", `{"dependencies":{"zod":"^3.22.0"}}`)
	write(t, pnpmDir, "pnpm-lock.yaml", `lockfileVersion: '9.0'

packages:
  zod@3.22.4:
    resolution: {integrity: sha512-abc}
`)
	if v, eco := ResolveVersion(pnpmDir, "zod"); v != "3.22.4" || eco != "npm" {
		t.Errorf("pnpm zod => %q,%q want 3.22.4,npm", v, eco)
	}
}

func TestLockfileExactGoSumCargoComposerPoetryPipfile(t *testing.T) {
	goDir := t.TempDir()
	write(t, goDir, "go.mod", "module x\n\ngo 1.22\n\nrequire github.com/spf13/cobra v1.8.0\n")
	write(t, goDir, "go.sum", `github.com/spf13/cobra v1.8.1 h1:abc=
github.com/spf13/cobra v1.8.1/go.mod h1:abc=
`)
	// go.sum lists 1.8.1; ResolveLockVersion should surface that exact pin.
	if v, eco, lf := ResolveLockVersion(goDir, "cobra"); v != "1.8.1" || eco != "go" || lf != "go.sum" {
		t.Errorf("go.sum cobra => %q,%q,%q want 1.8.1,go,go.sum", v, eco, lf)
	}
	if v, _ := ResolveVersion(goDir, "cobra"); v != "1.8.1" {
		t.Errorf("ResolveVersion should prefer go.sum over go.mod, got %q", v)
	}

	cargoDir := t.TempDir()
	write(t, cargoDir, "Cargo.toml", "[dependencies]\ntokio = \"1.0\"\n")
	write(t, cargoDir, "Cargo.lock", `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "tokio"
version = "1.40.0"
`)
	if v, eco := ResolveVersion(cargoDir, "tokio"); v != "1.40.0" || eco != "cargo" {
		t.Errorf("Cargo.lock tokio => %q,%q want 1.40.0,cargo", v, eco)
	}

	composerDir := t.TempDir()
	write(t, composerDir, "composer.json", `{"require":{"laravel/framework":"^11.0"}}`)
	write(t, composerDir, "composer.lock", `{
	  "packages": [{"name": "laravel/framework", "version": "v11.15.0"}],
	  "packages-dev": []
	}`)
	if v, eco := ResolveVersion(composerDir, "laravel/framework"); v != "11.15.0" || eco != "composer" {
		t.Errorf("composer.lock laravel => %q,%q want 11.15.0,composer", v, eco)
	}

	poetryDir := t.TempDir()
	write(t, poetryDir, "pyproject.toml", "[tool.poetry.dependencies]\ndjango = \"^5.0\"\n")
	write(t, poetryDir, "poetry.lock", `[[package]]
name = "django"
version = "5.0.3"
`)
	if v, eco := ResolveVersion(poetryDir, "django"); v != "5.0.3" || eco != "pip" {
		t.Errorf("poetry.lock django => %q,%q want 5.0.3,pip", v, eco)
	}

	pipDir := t.TempDir()
	write(t, pipDir, "Pipfile.lock", `{
	  "_meta": {"hash": {"sha256": "x"}},
	  "default": {"requests": {"version": "==2.31.0"}},
	  "develop": {}
	}`)
	if v, eco, lf := ResolveLockVersion(pipDir, "requests"); v != "2.31.0" || eco != "pip" || lf != "Pipfile.lock" {
		t.Errorf("Pipfile.lock requests => %q,%q,%q", v, eco, lf)
	}
}

func TestLockfileAbsentFallsBackToManifest(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "package.json", `{"dependencies":{"next":"^15.0.0"}}`)
	v, eco := ResolveVersion(dir, "next")
	if v != "15.0.0" || eco != "npm" {
		t.Errorf("manifest-only next => %q,%q want 15.0.0,npm", v, eco)
	}
	if _, _, lf := ResolveLockVersion(dir, "next"); lf != "" {
		t.Errorf("expected no lockfile, got %q", lf)
	}
}

func TestPackageLockV1DependenciesMap(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "package-lock.json", `{
	  "name": "app",
	  "lockfileVersion": 1,
	  "dependencies": {
	    "express": {"version": "4.18.2"}
	  }
	}`)
	if v, eco, lf := ResolveLockVersion(dir, "express"); v != "4.18.2" || eco != "npm" || lf != "package-lock.json" {
		t.Errorf("v1 lock express => %q,%q,%q", v, eco, lf)
	}
	// Ensure we didn't invent a fake path dependency on the temp dir itself.
	if _, err := filepath.Abs(dir); err != nil {
		t.Fatal(err)
	}
}
